// <auto-generated />
using System;
using AutoDealerExam.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoDealerExam.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260310094140_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("AutoDealerExam.Models.Automobil", b =>
                {
                    b.Property<int>("IdAutomobil")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnFabricatie")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Pret")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stoc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipCombustibil")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Transmisie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdAutomobil");

                    b.ToTable("Automobile");
                });

            modelBuilder.Entity("AutoDealerExam.Models.Client", b =>
                {
                    b.Property<int>("IdClient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prenume")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdClient");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Clienti");
                });

            modelBuilder.Entity("AutoDealerExam.Models.Comanda", b =>
                {
                    b.Property<int>("IdComanda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataComanda")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdAutomobil")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdClient")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StatusComanda")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdComanda");

                    b.HasIndex("IdAutomobil");

                    b.HasIndex("IdClient");

                    b.ToTable("Comenzi");
                });

            modelBuilder.Entity("AutoDealerExam.Models.Comanda", b =>
                {
                    b.HasOne("AutoDealerExam.Models.Automobil", "Automobil")
                        .WithMany("Comenzi")
                        .HasForeignKey("IdAutomobil")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AutoDealerExam.Models.Client", "Client")
                        .WithMany("Comenzi")
                        .HasForeignKey("IdClient")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Automobil");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("AutoDealerExam.Models.Automobil", b =>
                {
                    b.Navigation("Comenzi");
                });

            modelBuilder.Entity("AutoDealerExam.Models.Client", b =>
                {
                    b.Navigation("Comenzi");
                });
#pragma warning restore 612, 618
        }
    }
}
